# Generated by Django 6.0.3 on 2026-03-27 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_category_genre_alter_title_options_title_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Slug содержит недопустимые символы', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Slug категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Slug содержит недопустимые символы', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Slug жанра'),
        ),
    ]
