# Generated by Django 6.0.3 on 2026-03-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_category_slug_alter_genre_slug'),
        ('reviews', '0004_review_unique_review'),
    ]

    operations = [
    ]
