# Generated by Django 6.0.3 on 2026-03-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_20260327_1459'),
        ('reviews', '0005_merge_20260327_1505'),
    ]

    operations = [
    ]
