server {
    listen 80;
    server_name 158.160.247.104 kittygrammyau.hopto.org;

    server_tokens off;

    client_max_body_size 20M;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:9000; 
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:9000;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        root /staticfiles/;
        index  index.html index.htm;
        try_files $uri /index.html;
    }
}
